### ISSUE TITLE
ZIlPay roadmap

### ISSUE THREAD

**Issue by hicaru** [zilpay/zil-pay#90]
## ZilPay wallet 2023 roadmap:

- [x] Avely partnerships
- [x] TYRON partnerships
- [x] Encryption/Decryption API
- [ ] Update network controller (smart request)
- [x] migrate from `AES-128` to `AES-256` (Security level)
- [x] Add Password advanced settings for `PBKDF2` (Security level)
- [x] Launch SSN node
- [x] Update UI/UX
- [x] Build UI/UX for staking
- [x] Launch Staking DeFi, a new default tokens `stZIL`
- [ ] Add domain resolver by TYRON
- [ ] Rework ZIlPay mobile
